apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shiv9203/nginx:v2 ## (Enter Your Image name , If you try it you can use my image)
        ports:
        - containerPort: 80
