apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  MYSQL_DATABASE: "" ## (Enter Your Databases Name)
  MYSQL_USER: ""  ## ( Enter Your Username)
  MYSQL_HOST: ""  ## (Enter YOur Password)
